// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDeROGF3jhe3AYWlav3XUC8vsO6ROfMR0',
    appId: '1:201665574540:web:0593ba9a971ab837d12da9',
    messagingSenderId: '201665574540',
    projectId: 'movie-app-70a71',
    authDomain: 'movie-app-70a71.firebaseapp.com',
    storageBucket: 'movie-app-70a71.firebasestorage.app',
    measurementId: 'G-3W0CZSSPLK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzMFsdKfBLaref4j-niuI2_sgIUtFQUXs',
    appId: '1:201665574540:android:3290385197e0b08fd12da9',
    messagingSenderId: '201665574540',
    projectId: 'movie-app-70a71',
    storageBucket: 'movie-app-70a71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq0STfBz9YmoF-LbpdOOxMMkEb-V4ISQI',
    appId: '1:201665574540:ios:c95b8f783632096cd12da9',
    messagingSenderId: '201665574540',
    projectId: 'movie-app-70a71',
    storageBucket: 'movie-app-70a71.firebasestorage.app',
    iosBundleId: 'com.example.movieappnew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq0STfBz9YmoF-LbpdOOxMMkEb-V4ISQI',
    appId: '1:201665574540:ios:c95b8f783632096cd12da9',
    messagingSenderId: '201665574540',
    projectId: 'movie-app-70a71',
    storageBucket: 'movie-app-70a71.firebasestorage.app',
    iosBundleId: 'com.example.movieappnew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDeROGF3jhe3AYWlav3XUC8vsO6ROfMR0',
    appId: '1:201665574540:web:b7e03f819d15c23dd12da9',
    messagingSenderId: '201665574540',
    projectId: 'movie-app-70a71',
    authDomain: 'movie-app-70a71.firebaseapp.com',
    storageBucket: 'movie-app-70a71.firebasestorage.app',
    measurementId: 'G-79R174HNN1',
  );
}
